from django.urls import path, include
from .views import (
    DashboardDataView,
    UserView,
    TransactionView,
    MonthlyTransactionsView,
    NotificationView,
    BudgetView,
    ReportView,
    ChatbotView,
    UserRegistrationView,
    CustomTokenObtainPairView,
    ForgotPasswordView,
    CommentView,
    predict_category,
    TransactionCategoriesView,
)

urlpatterns = [
    path('api/register/', UserRegistrationView.as_view(), name='register'),
    path('api/login/', CustomTokenObtainPairView.as_view(), name='login'),
    path('api/user/', UserView.as_view(), name='user'),
    path('api/transactions/', TransactionView.as_view(), name='transactions'),
    path('api/forgot-password/', ForgotPasswordView.as_view(), name='forgot-password'),
    path('api/comments/', CommentView.as_view(), name='comments'),
    path('api/dashboard/', DashboardDataView.as_view(), name='dashboard'),
    path('api/notifications/', NotificationView.as_view(), name='notifications'),
    path('api/transactions/monthly/', MonthlyTransactionsView.as_view(), name='monthly-transactions'),
    path('api/transactions/<int:pk>/', TransactionView.as_view(), name='transaction-detail'),
    path('api/transaction-categories/', TransactionCategoriesView.as_view(), name='transaction-categories'),
    path('api/notifications/<int:pk>/', NotificationView.as_view(), name='notification-detail'),
    path('api/budgets/', BudgetView.as_view(), name='budgets'),
    path('api/reports/', ReportView.as_view(), name='reports'),
    path('api/chatbot/', ChatbotView.as_view(), name='chatbot'),
    path('api/categorize/', predict_category, name='predict_category'),
]